
name: Rebuild docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Source
      uses: actions/checkout@v2
      with:
        path: src
    - name: Clone Master
      uses: actions/checkout@v2
      with:
        ref: master
        path: dst
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install werkzeug
    - name: Rebuild
      run: |
        cd src
        make html
        cp -a _build/html/. ../dst
 
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        #author_name: Marc Demo (Github Actions)
        #author_email: i18n-bot@it-projects.info
        branch: master
        commit_message: | 
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/rebuild.yml )
        repository: dst
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
