
name: Rebuild docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Source
      uses: actions/checkout@v2
      with:
        path: src
    - name: Clone Master
      uses: actions/checkout@v2
      with:
        ref: master
        path: dst
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "Sphinx<2"
        pip install werkzeug
    - name: Rebuild
      run: |
        cd src
        make html SPHINXOPTS="-D language=ru -D languages=ru -D versions=13.0,12.0 -D canonical_root=/13.0"
        cp -a _build/html/. ../dst/12.0
 
    - name: Commit changes
      uses: yelizariev/git-auto-commit-action@custom-author-and-token2
      with:
        commit_author_name: Marc Demo (Github Actions)
        commit_author_email: i18n-bot@it-projects.info
        branch: master
        commit_message: | 
          :alien: recompile docs
          
          Sent from Github Actions (see .github/workflows/rebuild.yml )
        repository: dst
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
